### ISSUE TITLE
Unable to pull all Haskell dependencies from Nix store

### ISSUE THREAD

**Issue by morganthomas** [input-output-hk/plutus#3477]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[x] *Other* Any other topic (Playgrounds, etc.)

## Summary

For a project based on `plutus-starter`, Haskell dependencies do not get pulled from the Nix store when I would expect them to.

## Steps to reproduce

Clone `plutus-starter`. Run `nix-shell`. Run `cabal update`. Run `cabal build`.

## Expected behavior

If this has been done before on the same machine then it should pull the dependencies from the Nix store and thus not rebuild them.

## System info (please complete the following information):

- OS: NixOS
- Version 20.03
- Plutus version or commit hash: 5e20b2df3ac55b55b9d70eb7271b295ac797ed5e

## Additional context

I need help understanding how to build an efficient CI pipeline for a project using plutus-starter. I don't know if this is an issue with my reading of the docs, or the docs, or plutus-starter. I have written the following CI pipeline:

```
name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo=
          substituters = https://cache.nixos.org https://hydra.iohk.io https://iohk.cachix.org
    - run: nix-shell plutus-starter/shell.nix --command "cd plutus-starter; ./nix/style-check.sh"
    - run: nix-shell plutus-starter/shell.nix --command "cd plutus-starter; hlint ."
    - run: nix-shell plutus-starter/shell.nix --command "cd plutus-starter; cabal update; cabal run test:danaswap-spec"
    - run: nix-shell plutus-starter/shell.nix --command "cd plutus-starter; cabal update; cabal build plutus-starter-pab"
```

This pipeline is not failing, but the problem I'm having is that it's taking too long, because it's building lots and lots of dependencies. It is hitting the IOHK caches, and it's not building all the dependencies, but it exhibits the same behavior that it does on my local machine (NixOS 20.03), which is that if there is nothing cached in `dist-newstyle` then `cabal build` will build lots and lots of dependencies.

For me this is an issue with building a CI pipeline, but it's also a lesser issue for local development, because I am used to most or all of the dependencies I need being able to be cached by Nix.

The built-in CI pipeline of `plutus-starter` runs `release.nix`. I am not sure what this builds, but it doesn't seem to actually build the code of my project. I would like to check that my project builds into an executable file, and run hlint and style checks and unit tests. I would like to check that the nix-shell builds and thus that local development workflows will work. Does the CI included with `plutus-starter` cover these things, or does anybody know how I can modify it to cover these things without running into this issue of lots of dependencies being built after I enter the `nix-shell`?
